[package]
name = "ffmpeg-sidecar"
version = "1.2.0"
edition = "2021"
description = "Wrap a standalone FFmpeg binary in an intuitive Iterator interface."
authors = ["Nathan Babcock <nathan.r.babcock@gmail.com>"]
categories = ["multimedia"]
keywords = ["ffmpeg", "video"]
repository = "https://github.com/nathanbabcock/ffmpeg-sidecar"
readme = "README.md"
license = "MIT"

[features]
default = ["download_ffmpeg"]
download_ffmpeg = ["reqwest"]

[lib]
crate-type = ["lib"]

[dependencies]
anyhow = "1.0.79"
tar = "0.4.42"
zip = "2.2.0"
reqwest = { version = "0.12.8", optional = true, features = ["blocking"]}

